chore: general maintenance of scripts.

diff --git a/ova2qcow b/ova2qcow
--- a/ova2qcow
+++ b/ova2qcow
@@ -1,20 +1,28 @@
-#!/bin/bash
-# Josiah Bull - 23/11/2021
+#!/usr/bin/env bash
+
+# Author: Josiah Bull <josiah.bull7@gmail.com>
+# License: MIT/Apache-2.0
+
 # Convert ova file to qcow2
 
-if [ -z "$1" ] && [ test -f "$1" ]
+set -o errexit -o pipefail -o noclobber -o nounset
+
+if [ -z "$1" ] || ! test -f "$1"
 then
-    echo "Invalid or no file provided."
+    echo "Invalid or no file provided." >&2
+    exit 1
 else
-    #Generate directory to hold conversion data
-    echo "Attempting to open file " $1
-    path="./${1}-conversiondata"
-    mkdir -p "${path}"
-    #Unzip files
-    tar -xvf "./${1}" -C "${path}"
-    files=( "${path}"/*.vmdk )
-    #Convert to qcow
-    qemu-img convert "${files[0]}" "${1}-img.qcow2"
-    #Remove temporary files
-    rm -rd "${path}"
+    # Generate directory to hold conversion data
+    tmp_dir=$(mktemp -d)
+    function cleanup {
+        rm -rf "${tmp_dir}"
+    }
+    trap cleanup EXIT
+
+    # Unzip files
+    tar -xvf "./${1}" -C "${tmp_dir}"
+    files=( "${tmp_dir}"/*.vmdk )
+
+    # Convert to qcow
+    qemu-img convert "${files[0]}" "${1}-img.qcow2" >&2
 fi
diff --git a/partly/build-devbox b/partly/build-devbox
--- a/partly/build-devbox
+++ b/partly/build-devbox
@@ -1,38 +1,37 @@
-#!/bin/bash
-# FILEPATH: /home/josiah/.scripts/build-devbox
+#!/usr/bin/env bash
 
-set -e
-set -o pipefail
+# Author: Josiah Bull <josiah.bull7@gmail.com>
+# License: MIT/Apache-2.0
 
-LOGFILE="/home/josiah/.scripts/build-devbox.log"
+set -o errexit -o pipefail -o noclobber -o nounset
+
 DOCKER_USER="robot\$devbox"
 DOCKER_PASS="$(cat ~/.docker/.env)"
 DEVBOX_CONTAINER_NAME="devbox_$(whoami)-devbox-1"
-DEVBOX_IMAGE_NAME="harbor.partly.pro/partly/devbox:latest"
 BUILDBOX_IMAGE_NAME="harbor.partly.pro/partly/buildbox:latest"
-BUILD_DIR="/home/josiah/Documents/partly"
+BUILD_DIR="$HOME/Documents/partly"
 
-echo "Starting devbox reset..." | tee -a $LOGFILE
+echo "Starting devbox reset..." >&2
 
 if ! docker info >/dev/null 2>&1; then
-    echo "Docker is not running. Please start Docker and try again." | tee -a $LOGFILE
+    echo "Docker is not running. Please start Docker and try again." >&2
     exit 1
 fi
 
 # Check if there is an existing devbox container running
-if [ "$(docker ps -q -f name=$DEVBOX_CONTAINER_NAME)" ]; then
-    echo "Stopping running devbox container..." | tee -a $LOGFILE
-    docker stop $DEVBOX_CONTAINER_NAME || echo "Error stopping devbox container" >&2
+if [ "$(docker ps -q -f name="$DEVBOX_CONTAINER_NAME")" ]; then
+    echo "Stopping running devbox container..." >&2
+    docker stop "$DEVBOX_CONTAINER_NAME" || echo "Error stopping devbox container" >&2
 fi
 
 # Remove the existing containers
-if [ "$(docker ps -a -q -f name=$DEVBOX_CONTAINER_NAME)" ]; then
-    echo "Removing existing devbox container..." | tee -a $LOGFILE
-    docker rm $DEVBOX_CONTAINER_NAME || echo "Error removing devbox container" >&2
+if [ "$(docker ps -a -q -f name="$DEVBOX_CONTAINER_NAME")" ]; then
+    echo "Removing existing devbox container..." >&2
+    docker rm "$DEVBOX_CONTAINER_NAME" || echo "Error removing devbox container" >&2
 fi
 
 if [ "$(docker ps -a -q -f name=$BUILDBOX_IMAGE_NAME)" ]; then
-    echo "Removing existing buildbox container..." | tee -a $LOGFILE
+    echo "Removing existing buildbox container..." >&2
     docker rm $BUILDBOX_IMAGE_NAME || echo "Error removing buildbox container" >&2
 fi
 
@@ -43,7 +42,7 @@ docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" harbor.partly.pro || echo "Erro
 sleep 1
 
 # Build Buildbox
-pushd $BUILD_DIR || echo "Error pushing build dir onto directory stack" >&2
+pushd "$BUILD_DIR" || echo "Error pushing build dir onto directory stack" >&2
 echo "Building Buildbox Container..."
 ./pipeline/build.sh buildbox
 echo "BuildBox Container built successfully."
@@ -55,7 +54,7 @@ popd || echo "Error popping build dir off directory stack" >&2
 # Start Devbox
 echo "Starting Devbox..."
 current_dir=$(pwd)
-cd $BUILD_DIR
-./devbox zsh && cd $current_dir || echo "Error starting zsh" >&2
+cd "$BUILD_DIR"
+./devbox zsh && cd "$current_dir" || echo "Error starting zsh" >&2
 
-echo "Devbox reset completed." | tee -a $LOGFILE
+echo "Devbox reset completed." >&2
